services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: blogbowl
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
    volumes:
      - bb_postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - blogbowl_redis_data:/data
    ports:
      - "6380:6379"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M

volumes:
  bb_postgres_data:
  blogbowl_redis_data:
