services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_MULTIPLE_DATABASES: blogbowl,analytics
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
    volumes:
      - ./dev/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
      - bb_postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M

volumes:
  bb_postgres_data:
