development:
  db:
    username: development
    password: development
    host: localhost
    port: 5432
  pages_base_domain: 'localost'
  frontend_url: 'http://localhost:3000'
  postmark:
    account_token:
    x_api_key:
  smtp:
    address:
    port:
    domain:
    user_name:
    password:
    authentication:
    enable_starttls_auto:
  s3:
    access_key_id:
    secret_access_key:
    endpoint:
    region:
    bucket:

production:
  db:
    username: blogbowl
    password: blogbowl
    host: postgres
    port: 5432
  pages_base_domain: 'localhost'
  frontend_url: 'http://localhost:3000'
  redis_url: 'redis://redis:6379/1'
  postmark:
    account_token:
    x_api_key:
  smtp:
    address:
    port:
    domain:
    user_name:
    password:
    authentication:
    enable_starttls_auto:
  s3:
    access_key_id:
    secret_access_key:
    endpoint:
    region:
    bucket:

test:
  db:
    username: development
    password: development
    host: localhost
    port: 5432
  pages_base_domain: 'localost'
  frontend_url: 'http://localhost:3000'
  postmark:
    account_token:
    x_api_key:
  smtp:
    address:
    port:
    domain:
    user_name:
    password:
    authentication:
    enable_starttls_auto:
  s3:
    access_key_id:
    secret_access_key:
    endpoint:
    region:
    bucket:

